### ISSUE TITLE
[Dayton Allemann, HSCC] <Error 503 Backend fetch failed in https://eclkc.ohs.acf.hhs.gov/cc/admin>

### ISSUE THREAD

**Issue by uwohscc** [OHS-Hosting-Infrastructure/infrastructure#149]
## Reported By
Dayton Allemann

## Application Context
Coaching Companion

## Environment Context
Production
## Describe the issue
The site does not load. Getting this Varnish error: 
Error 503 Backend fetch failed
Backend fetch failed

Guru Meditation:
XID: 525007

## Impact
All users of the Coaching Companion site cannot use

### Reproducibility
Always

### Steps to reproduce the behavior:
1. Go to 'https://eclkc.ohs.acf.hhs.gov/cc/admin'

## Expected Behavior
A login page would load.

**Comment by uwohscc** [comment]
Bump: I need to know if anyone has seen this.

**Comment by uwohscc** [comment]
Sorry; disregard the last comment; I see that the site is loading.

**Comment by uwohscc** [comment]
I will be away from my desk until 7am Pacific on July 23rd. The site is currently working, but the last Git commit has not been incorporated. I'll check on the site at around 7am Pacific on July 23rd.

**Comment by eeeady** [comment]
Hi Dayton,

Sorry I didn't see this earlier. The site was working last night but I can't check https://eclkc.ohs.acf.hhs.gov/cc/admin since I'm not sure I either have the permissions or the understanding of what I should see there..

Just did another git pull. Maybe I pulled in the wrong location last night? Could you please check that what is there is what you would expect?

Thanks!

**Comment by rpdelaney** [comment]
Since we have moved work tracking to JIRA, I am closing open issues in this repo via a script.
